[project]
name = "pytorch-cuda-operator"
version = "0.1.0"
description = "Template for writing CUDA operators in pytorch"
authors = [{ name = "Simon Draeger", email = "sdraeger@salk.edu" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
